#! /bin/sh

# INITIAL SETUP =================
# this fixes burpsuite and ghidra jesus christ abatakaaaaaaam
wmname LG3D &

# set wallpaper
feh --bg-fill /home/otter/Desktop/archRice/allWallpapers/hacknet.jpg

# Check if second monitor is connected and activate it
/home/otter/Desktop/archRice/hacknet/sxhkd/2screen.sh

# Start polybar
$HOME/.config/polybar/launch.sh

# Launch notification daemon
dunst -config $HOME/.config/dunstrc &

# Load notification dunst configuration file
/home/otter/.config/dunst/reload

# Set up environment
pgrep -x sxhkd > /dev/null || sxhkd &

# Fix pointer
xsetroot -cursor_name left_ptr

# Start compositor
#while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
#picom  --config $HOME/.config/picom.conf

# Assign different workspaces to the monitors
#bspc monitor eDP-1 -d 一 二 三 四 五
#bspc monitor HDMI-1 -d 六 七 八 九 十
#bspc monitor eDP-1 -d 1 2 3 4 5
#bspc monitor HDMI-1 -d 6 7 8 9 10

# BSPWM SETTINGS =================

# disable sloppy mouse focus
bspc config focus_follows_pointer false

bspc config border_width         1
bspc config window_gap           5
bspc config split_ratio		 0.50

bspc config focused_border_color "#e0e0e0"
bspc config normal_border_color "#1a1b26"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
#bspc config focus_follows_pointer true

# Add rules for programs
#	check attributes with `xprop`

# How to restrict windows to workspaces
#declare -a terminal=(Alacritty Xfce4-terminal)
#for i in ${terminal[@]}; do
#	    bspc rule -a $i desktop='^1' follow=on focus=on; done
